// Code generated by maint/generate-dispatch. DO NOT EDIT.

package main

import (
	"io"

	"github.com/frioux/leatherman/internal/tool/amygdala"
	"github.com/frioux/leatherman/internal/tool/automoji"
	"github.com/frioux/leatherman/internal/tool/backlight"
	"github.com/frioux/leatherman/internal/tool/bamboo"
	"github.com/frioux/leatherman/internal/tool/brainstem"
	"github.com/frioux/leatherman/internal/tool/clocks"
	"github.com/frioux/leatherman/internal/tool/csv"
	"github.com/frioux/leatherman/internal/tool/debounce"
	"github.com/frioux/leatherman/internal/tool/dumpmozlz4"
	"github.com/frioux/leatherman/internal/tool/email"
	"github.com/frioux/leatherman/internal/tool/expandurl"
	"github.com/frioux/leatherman/internal/tool/fn"
	"github.com/frioux/leatherman/internal/tool/groupbydate"
	"github.com/frioux/leatherman/internal/tool/minotaur"
	"github.com/frioux/leatherman/internal/tool/netrcpassword"
	"github.com/frioux/leatherman/internal/tool/notes"
	"github.com/frioux/leatherman/internal/tool/pomotimer"
	"github.com/frioux/leatherman/internal/tool/prependhist"
	"github.com/frioux/leatherman/internal/tool/proj"
	"github.com/frioux/leatherman/internal/tool/replaceunzip"
	"github.com/frioux/leatherman/internal/tool/slack"
	"github.com/frioux/leatherman/internal/tool/smlist"
	"github.com/frioux/leatherman/internal/tool/srv"
	"github.com/frioux/leatherman/internal/tool/status"
	"github.com/frioux/leatherman/internal/tool/toml"
	"github.com/frioux/leatherman/internal/tool/twilio"
	"github.com/frioux/leatherman/internal/tool/uni"
	"github.com/frioux/leatherman/internal/tool/update"
	"github.com/frioux/leatherman/internal/tool/wuphf"
	"github.com/frioux/leatherman/internal/tool/yaml"
	"github.com/frioux/leatherman/internal/tool/zine"
)

func init() {
	Dispatch = map[string]func([]string, io.Reader) error{
		"addrs":                email.Addrs,
		"addrspec-to-tabs":     email.ToTabs,
		"alluni":               uni.All,
		"amygdala":             amygdala.Amygdala,
		"auto-emote":           automoji.Run,
		"backlight":            backlight.Run,
		"brainstem":            brainstem.Brainstem,
		"clocks":               clocks.Run,
		"csv2json":             csv.ToJSON,
		"csv2md":               csv.ToMarkdown,
		"debounce":             debounce.Run,
		"dump-mozlz4":          dumpmozlz4.Run,
		"email2json":           email.ToJSON,
		"expand-url":           expandurl.Run,
		"export-bamboohr":      bamboo.ExportDirectory,
		"export-bamboohr-tree": bamboo.ExportOrgChart,
		"fn":                   fn.Run,
		"group-by-date":        groupbydate.Run,
		"minotaur":             minotaur.Run,
		"name2rune":            uni.ToRune,
		"netrc-password":       netrcpassword.Run,
		"notes":                notes.Serve,
		"pomotimer":            pomotimer.Run,
		"prepend-hist":         prependemojihist.Run,
		"proj":                 proj.Proj,
		"render-mail":          email.Render,
		"replace-unzip":        replaceunzip.Run,
		"slack-deaddrop":       slack.Deaddrop,
		"slack-open":           slack.Open,
		"slack-status":         slack.Status,
		"sm-list":              smlist.Run,
		"srv":                  srv.Serve,
		"status":               status.Status,
		"toml2json":            toml.ToJSON,
		"twilio":               twilio.Twilio,
		"uni":                  uni.Describe,
		"update":               update.Update,
		"wuphf":                wuphf.Wuphf,
		"yaml2json":            yaml.ToJSON,
		"zine":                 zine.Run,

		"help":    Help,
		"version": Version,
		"explode": Explode,
	}
}
