#!/usr/bin/perl

use strict;
use autodie;

open my $fh, '>', 'pal.go';

print $fh <<'GO';
package status

import "image/color"

func init() {
	palettes = [][]color.NRGBA{
GO

my @p = (
   'https://coolors.co/palette/9b5de5-f15bb5-fee440-00bbf9-00f5d4',
   'https://coolors.co/palette/177e89-084c61-db3a34-ffc857-323031',
   'https://coolors.co/palette/0c0f0a-ff206e-fbff12-41ead4-ffffff',
   'https://coolors.co/palette/000814-001d3d-003566-ffc300-ffd60a',
   'https://coolors.co/palette/f72585-7209b7-3a0ca3-4361ee-4cc9f0',
   'https://coolors.co/palette/003049-d62828-f77f00-fcbf49-eae2b7',
   'https://coolors.co/palette/606c38-283618-fefae0-dda15e-bc6c25',
   'https://coolors.co/palette/ffbe0b-fb5607-ff006e-8338ec-3a86ff',
);

my $i = 0;
for my $p (@p) {
   print $fh "\t\t// $p\n";
   print $fh "\t\t$i: {\n";
   for my $c ($p =~ m/[0-9a-f]{6}/gc) {
      my ($r, $g, $b) = ($c =~ m/(..)(..)(..)/);
      print $fh "\t\t\tcolor.NRGBA{0x$r, 0x$g, 0x$b, 0xff},\n",
   }
   print $fh "\t\t},\n";
   $i++;
}

print $fh <<'GO'
	}
}
GO
